export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const ADD_CANDIDATE_REQUEST = "ADD_CANDIDATE_REQUEST";
export const ADD_CANDIDATE_SUCCESS = "ADD_CANDIDATE_SUCCESS";
export const ADD_CANDIDATE_FAILURE = "ADD_CANDIDATE_FAILURE";

export const ADD_INTERVIEW_REQUEST = "ADD_INTERVIEW_REQUEST";
export const ADD_INTERVIEW_SUCCESS = "ADD_INTERVIEW_SUCCESS";
export const ADD_INTERVIEW_FAILURE = "ADD_INTERVIEW_FAILURE";


