export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const ADD_CANDIDATE_REQUEST = "ADD_CANDIDATE_REQUEST";
export const ADD_CANDIDATE_SUCCESS = "ADD_CANDIDATE_SUCCESS";
export const ADD_CANDIDATE_FAILURE = "ADD_CANDIDATE_FAILURE";

export const VIEW_CANDIDATE_REQUEST = "VIEW_CANDIDATE_REQUEST";
export const VIEW_CANDIDATE_SUCCESS = "VIEW_CANDIDATE_SUCCESS";
export const VIEW_CANDIDATE_FAILURE = "VIEW_CANDIDATE_FAILURE";

export const ADD_INTERVIEW_REQUEST = "ADD_INTERVIEW_REQUEST";
export const ADD_INTERVIEW_SUCCESS = "ADD_INTERVIEW_SUCCESS";
export const ADD_INTERVIEW_FAILURE = "ADD_INTERVIEW_FAILURE";

export const ADD_INTERVIEWER_REQUEST = "ADD_INTERVIEWER_REQUEST";
export const ADD_INTERVIEWER_SUCCESS = "ADD_INTERVIEWER_SUCCESS";
export const ADD_INTERVIEWER_FAILURE = "ADD_INTERVIEWER_FAILURE";

export const UPDATE_INTERVIEW_REQUEST = "UPDATE_INTERVIEW_REQUEST";
export const UPDATE_INTERVIEW_SUCCESS = "UPDATE_INTERVIEW_SUCCESS";
export const UPDATE_INTERVIEW_FAILURE = "UPDATE_INTERVIEW_FAILURE";

export const VIEW_INTERVIEW_REQUEST = "VIEW_INTERVIEW_REQUEST";
export const VIEW_INTERVIEW_SUCCESS = "VIEW_INTERVIEW_SUCCESS";
export const VIEW_INTERVIEW_FAILURE = "VIEW_INTERVIEW_FAILURE";

export const GET_INTERVIEW_BY_ID_REQUEST = "GET_INTERVIEW_BY_ID_REQUEST";
export const GET_INTERVIEW_BY_ID_SUCCESS = "GET_INTERVIEW_BY_ID_SUCCESS";
export const GET_INTERVIEW_BY_ID_FAILURE = "GET_INTERVIEW_BY_ID_FAILURE";

export const VIEW_SOURCE_REQUEST = "VIEW_SOURCE_REQUEST";
export const VIEW_SOURCE_SUCCESS = "VIEW_SOURCE_SUCCESS";
export const VIEW_SOURCE_FAILURE = "VIEW_SOURCE_FAILURE";


export const VIEW_SKILL_TYPE_REQUEST = "VIEW_SKILL_TYPE_REQUEST";
export const VIEW_SKILL_TYPE_SUCCESS = "VIEW_SKILL_TYPE_SUCCESS";
export const VIEW_SKILL_TYPE_FAILURE = "VIEW_SKILL_TYPE_FAILURE";

export const VIEW_ACTIVE_SKILL_REQUEST = "VIEW_ACTIVE_SKILL_REQUEST";
export const VIEW_ACTIVE_SKILL_SUCCESS = "VIEW_ACTIVE_SKILL_SUCCESS";
export const VIEW_ACTIVE_SKILL_FAILURE = "VIEW_ACTIVE_SKILL_FAILURE";

export const VIEW_ACTIVE_INTERVIEW_MODE_REQUEST = "VIEW_ACTIVE_INTERVIEW_MODE_REQUEST";
export const VIEW_ACTIVE_INTERVIEW_MODE_SUCCESS = "VIEW_ACTIVE_INTERVIEW_MODE_SUCCESS";
export const VIEW_ACTIVE_INTERVIEW_MODE_FAILURE = "VIEW_ACTIVE_INTERVIEW_MODE_FAILURE";

export const VIEW_ACTIVE_DEGREE_REQUEST = "VIEW_ACTIVE_DEGREE_REQUEST";
export const VIEW_ACTIVE_DEGREE_SUCCESS = "VIEW_ACTIVE_DEGREE_SUCCESS";
export const VIEW_ACTIVE_DEGREE_FAILURE = "VIEW_ACTIVE_DEGREE_FAILURE";



