const Constants = {

    BASEURL: 'http://127.0.0.1:8000/api/',


    USER_LOG_IN_REQUEST: 'USER_LOG_IN_REQUEST',
    USER_LOG_IN_SUCESS: 'USER_LOG_IN_SUCESS',
    USER_LOG_IN_FAILED: 'USER_LOG_IN_FAILED',


    CREATE_NEW_USER_REQUEST: 'CREATE_NEW_USER_REQUEST',
    CREATE_NEW_USER_SUCESS: 'CREATE_NEW_USER_SUCESS',
    CREATE_NEW_USER_FAILED: 'CREATE_NEW_USER_FAILED',

    REMOVE_USER_REQUEST: 'REMOVE_USER_REQUEST',
    REMOVE_USER_SUCESS: 'REMOVE_USER_SUCESS',
    REMOVE_USER_FAILED: 'REMOVE_USER_FAILED',

    GET_ALL_USER_REQUEST: 'GET_ALL_USER_REQUEST',
    GET_ALL_USER_SUCESS: 'GET_ALL_USER_SUCESS',
    GET_ALL_USER_FAILED: 'GET_ALL_USER_FAILED',

    USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
    USER_LOGOUT_SUCESS: 'USER_LOGOUT_SUCESS',
    USER_LOGOUT_FAILED: 'USER_LOGOUT_FAILED',



    // CANDIDATES
    GET_ALL_CANDIDATES_REQUEST: 'GET_ALL_CANDIDATES_REQUEST',
    GET_ALL_CANDIDATES_SUCESS: 'GET_ALL_CANDIDATES_SUCESS',
    GET_ALL_CANDIDATES_FAILED: 'GET_ALL_CANDIDATES_FAILED',

    GET_CANDIDATES_BY_ID_REQUEST: 'GET_CANDIDATES_BY_ID_REQUEST',
    GET_CANDIDATES_BY_ID_SUCESS: 'GET_CANDIDATES_BY_ID_SUCESS',
    GET_CANDIDATES_BY_ID_FAILED: 'GET_CANDIDATES_BY_ID_FAILED',

    ADD_CANDIDATES_REQUEST: 'ADD_CANDIDATES_REQUEST',
    ADD_CANDIDATES_SUCESS: 'ADD_CANDIDATES_SUCESS',
    ADD_CANDIDATES_FAILED: 'ADD_CANDIDATES_FAILED',

    UPDATE_CANDIDATES_REQUEST: 'UPDATE_CANDIDATES_REQUEST',
    UPDATE_CANDIDATES_SUCESS: 'UPDATE_CANDIDATES_SUCESS',
    UPDATE_CANDIDATES_FAILED: 'UPDATE_CANDIDATES_FAILED',

    REMOVE_CANDIDATES_REQUEST: 'REMOVE_CANDIDATES_REQUEST',
    REMOVE_CANDIDATES_SUCESS: 'REMOVE_CANDIDATES_SUCESS',
    REMOVE_CANDIDATES_FAILED: 'REMOVE_CANDIDATES_FAILED',

    GET_CANDIDATES_ENUMS_REQUEST: 'GET_CANDIDATES_ENUMS_REQUEST',
    GET_CANDIDATES_ENUMS_SUCESS: 'GET_CANDIDATES_ENUMS_SUCESS',
    GET_CANDIDATES_ENUMS_FAILED: 'GET_CANDIDATES_ENUMS_FAILED',

    // Interviews
    GET_ALL_INTERVIEWS_REQUEST: 'GET_ALL_INTERVIEWS_REQUEST',
    GET_ALL_INTERVIEWS_SUCESS: 'GET_ALL_INTERVIEWS_SUCESS',
    GET_ALL_INTERVIEWS_FAILED: 'GET_ALL_INTERVIEWS_FAILED',

    GET_INTERVIEWS_BY_ID_REQUEST: 'GET_INTERVIEWS_BY_ID_REQUEST',
    GET_INTERVIEWS_BY_ID_SUCESS: 'GET_INTERVIEWS_BY_ID_SUCESS',
    GET_INTERVIEWS_BY_ID_FAILED: 'GET_INTERVIEWS_BY_ID_FAILED',

    ADD_INTERVIEWS_REQUEST: 'ADD_INTERVIEWS_REQUEST',
    ADD_INTERVIEWS_SUCESS: 'ADD_INTERVIEWS_SUCESS',
    ADD_INTERVIEWS_FAILED: 'ADD_INTERVIEWS_FAILED',

    UPDATE_INTERVIEWS_REQUEST: 'UPDATE_INTERVIEWS_REQUEST',
    UPDATE_INTERVIEWS_SUCESS: 'UPDATE_INTERVIEWS_SUCESS',
    UPDATE_INTERVIEWS_FAILED: 'UPDATE_INTERVIEWS_FAILED',

    REMOVE_INTERVIEWS_REQUEST: 'REMOVE_INTERVIEWS_REQUEST',
    REMOVE_INTERVIEWS_SUCESS: 'REMOVE_INTERVIEWS_SUCESS',
    REMOVE_INTERVIEWS_FAILED: 'REMOVE_INTERVIEWS_FAILED',

    // SKIL
    GET_ALL_SKILL_REQUEST: 'GET_ALL_SKILL_REQUEST',
    GET_ALL_SKILL_SUCESS: 'GET_ALL_SKILL_SUCESS',
    GET_ALL_SKILL_FAILED: 'GET_ALL_SKILL_FAILED',

    GET_ACTIVE_SKILL_REQUEST: 'GET_ACTIVE_SKILL_REQUEST',
    GET_ACTIVE_SKILL_SUCESS: 'GET_ACTIVE_SKILL_SUCESS',
    GET_ACTIVE_SKILL_FAILED: 'GET_ACTIVE_SKILL_FAILED',

    GET_SKILL_BY_ID_REQUEST: 'GET_SKILL_BY_ID_REQUEST',
    GET_SKILL_BY_ID_SUCESS: 'GET_SKILL_BY_ID_SUCESS',
    GET_SKILL_BY_ID_FAILED: 'GET_SKILL_BY_ID_FAILED',

    ADD_SKILL_REQUEST: 'ADD_SKILL_REQUEST',
    ADD_SKILL_SUCESS: 'ADD_SKILL_SUCESS',
    ADD_SKILL_FAILED: 'ADD_SKILL_FAILED',

    UPDATE_SKILL_REQUEST: 'UPDATE_SKILL_REQUEST',
    UPDATE_SKILL_SUCESS: 'UPDATE_SKILL_SUCESS',
    UPDATE_SKILL_FAILED: 'UPDATE_SKILL_FAILED',

    REMOVE_SKILL_REQUEST: 'REMOVE_SKILL_REQUEST',
    REMOVE_SKILL_SUCESS: 'REMOVE_SKILL_SUCESS',
    REMOVE_SKILL_FAILED: 'REMOVE_SKILL_FAILED',

    // SKIL TYPE
    GET_ALL_SKILL_TYPE_REQUEST: 'GET_ALL_SKILL_TYPE_REQUEST',
    GET_ALL_SKILL_TYPE_SUCESS: 'GET_ALL_SKILL_TYPE_SUCESS',
    GET_ALL_SKILL_TYPE_FAILED: 'GET_ALL_SKILL_TYPE_FAILED',

    GET_SKILL_TYPE_BY_ID_REQUEST: 'GET_SKILL_TYPE_BY_ID_REQUEST',
    GET_SKILL_TYPE_BY_ID_SUCESS: 'GET_SKILL_TYPE_BY_ID_SUCESS',
    GET_SKILL_TYPE_BY_ID_FAILED: 'GET_SKILL_TYPE_BY_ID_FAILED',

    ADD_SKILL_TYPE_REQUEST: 'ADD_SKILL_TYPE_REQUEST',
    ADD_SKILL_TYPE_SUCESS: 'ADD_SKILL_TYPE_SUCESS',
    ADD_SKILL_TYPE_FAILED: 'ADD_SKILL_TYPE_FAILED',

    UPDATE_SKILL_TYPE_REQUEST: 'UPDATE_SKILL_TYPE_REQUEST',
    UPDATE_SKILL_TYPE_SUCESS: 'UPDATE_SKILL_TYPE_SUCESS',
    UPDATE_SKILL_TYPE_FAILED: 'UPDATE_SKILL_TYPE_FAILED',

    REMOVE_SKILL_TYPE_REQUEST: 'REMOVE_SKILL_TYPE_REQUEST',
    REMOVE_SKILL_TYPE_SUCESS: 'REMOVE_SKILL_TYPE_SUCESS',
    REMOVE_SKILL_TYPE_FAILED: 'REMOVE_SKILL_TYPE_FAILED',

    // Source
    GET_ALL_SOURCE_REQUEST: 'GET_ALL_SOURCE_REQUEST',
    GET_ALL_SOURCE_SUCESS: 'GET_ALL_SOURCE_SUCESS',
    GET_ALL_SOURCE_FAILED: 'GET_ALL_SOURCE_FAILED',

    GET_ACTIVE_SOURCE_REQUEST: 'GET_ACTIVE_SOURCE_REQUEST',
    GET_ACTIVE_SOURCE_SUCESS: 'GET_ACTIVE_SOURCE_SUCESS',
    GET_ACTIVE_SOURCE_FAILED: 'GET_ACTIVE_SOURCE_FAILED',

    ADD_SOURCE_BY_ID_REQUEST: 'ADD_SOURCE_BY_ID_REQUEST',
    ADD_SOURCE_BY_ID_SUCESS: 'ADD_SOURCE_BY_ID_SUCESS',
    ADD_SOURCE_BY_ID_FAILED: 'ADD_SOURCE_BY_ID_FAILED',

    ADD_SOURCE_REQUEST: 'ADD_SOURCE_REQUEST',
    ADD_SOURCE_SUCESS: 'ADD_SOURCE_SUCESS',
    ADD_SOURCE_FAILED: 'ADD_SOURCE_FAILED',

    UPDATE_SOURCE_REQUEST: 'UPDATE_SOURCE_REQUEST',
    UPDATE_SOURCE_SUCESS: 'UPDATE_SOURCE_SUCESS',
    UPDATE_SOURCE_FAILED: 'UPDATE_SOURCE_FAILED',

    REMOVE_SOURCE_REQUEST: 'REMOVE_SOURCE_REQUEST',
    REMOVE_SOURCE_SUCESS: 'REMOVE_SOURCE_SUCESS',
    REMOVE_SOURCE_FAILED: 'REMOVE_SOURCE_FAILED',

    // Interviewer List
    GET_ALL_INTERVIEWER_REQUEST: 'GET_ALL_INTERVIEWER_REQUEST',
    GET_ALL_INTERVIEWER_SUCESS: 'GET_ALL_INTERVIEWER_SUCESS',
    GET_ALL_INTERVIEWER_FAILED: 'GET_ALL_INTERVIEWER_FAILED',

    GET_ACTIVE_INTERVIEWER_REQUEST: 'GET_ACTIVE_INTERVIEWER_REQUEST',
    GET_ACTIVE_INTERVIEWER_SUCESS: 'GET_ACTIVE_INTERVIEWER_SUCESS',
    GET_ACTIVE_INTERVIEWER_FAILED: 'GET_ACTIVE_INTERVIEWER_FAILED',

    ADD_INTERVIEWER_REQUEST: 'ADD_INTERVIEWER_REQUEST',
    ADD_INTERVIEWER_SUCESS: 'ADD_INTERVIEWER_SUCESS',
    ADD_INTERVIEWER_FAILED: 'ADD_INTERVIEWER_FAILED',

    UPDATE_INTERVIEWER_REQUEST: 'UPDATE_INTERVIEWER_REQUEST',
    UPDATE_INTERVIEWER_SUCESS: 'UPDATE_INTERVIEWER_SUCESS',
    UPDATE_INTERVIEWER_FAILED: 'UPDATE_INTERVIEWER_FAILED',

    REMOVE_INTERVIEWER_REQUEST: 'REMOVE_INTERVIEWER_REQUEST',
    REMOVE_INTERVIEWER_SUCESS: 'REMOVE_INTERVIEWER_SUCESS',
    REMOVE_INTERVIEWER_FAILED: 'REMOVE_INTERVIEWER_FAILED',

    // Recruitment Status Master
    GET_ALL_RECRUITMENT_STATUS_REQUEST: 'GET_ALL_RECRUITMENT_STATUS_REQUEST',
    GET_ALL_RECRUITMENT_STATUS_SUCESS: 'GET_ALL_RECRUITMENT_STATUS_SUCESS',
    GET_ALL_RECRUITMENT_STATUS_FAILED: 'GET_ALL_RECRUITMENT_STATUS_FAILED',

    GET_ACTIVE_RECRUITMENT_STATUS_REQUEST: 'GET_ACTIVE_RECRUITMENT_STATUS_REQUEST',
    GET_ACTIVE_RECRUITMENT_STATUS_SUCESS: 'GET_ACTIVE_RECRUITMENT_STATUS_SUCESS',
    GET_ACTIVE_RECRUITMENT_STATUS_FAILED: 'GET_ACTIVE_RECRUITMENT_STATUS_FAILED',

    ADD_RECRUITMENT_STATUS_REQUEST: 'ADD_RECRUITMENT_STATUS_REQUEST',
    ADD_RECRUITMENT_STATUS_SUCESS: 'ADD_RECRUITMENT_STATUS_SUCESS',
    ADD_RECRUITMENT_STATUS_FAILED: 'ADD_RECRUITMENT_STATUS_FAILED',

    UPDATE_RECRUITMENT_STATUS_REQUEST: 'UPDATE_RECRUITMENT_STATUS_REQUEST',
    UPDATE_RECRUITMENT_STATUS_SUCESS: 'UPDATE_RECRUITMENT_STATUS_SUCESS',
    UPDATE_RECRUITMENT_STATUS_FAILED: 'UPDATE_RECRUITMENT_STATUS_FAILED',

    REMOVE_RECRUITMENT_STATUS_REQUEST: 'REMOVE_RECRUITMENT_STATUS_REQUEST',
    REMOVE_RECRUITMENT_STATUS_SUCESS: 'REMOVE_RECRUITMENT_STATUS_SUCESS',
    REMOVE_RECRUITMENT_STATUS_FAILED: 'REMOVE_RECRUITMENT_STATUS_FAILED',

    // Recruitment Status Master
    GET_ALL_MODE_OF_WORK_REQUEST: 'GET_ALL_MODE_OF_WORK_REQUEST',
    GET_ALL_MODE_OF_WORK_SUCESS: 'GET_ALL_MODE_OF_WORK_SUCESS',
    GET_ALL_MODE_OF_WORK_FAILED: 'GET_ALL_MODE_OF_WORK_FAILED',

    GET_ACTIVE_MODE_OF_WORK_REQUEST: 'GET_ACTIVE_MODE_OF_WORK_REQUEST',
    GET_ACTIVE_MODE_OF_WORK_SUCESS: 'GET_ACTIVE_MODE_OF_WORK_SUCESS',
    GET_ACTIVE_MODE_OF_WORK_FAILED: 'GET_ACTIVE_MODE_OF_WORK_FAILED',

    ADD_MODE_OF_WORK_REQUEST: 'ADD_MODE_OF_WORK_REQUEST',
    ADD_MODE_OF_WORK_SUCESS: 'ADD_MODE_OF_WORK_SUCESS',
    ADD_MODE_OF_WORK_FAILED: 'ADD_MODE_OF_WORK_FAILED',

    UPDATE_MODE_OF_WORK_REQUEST: 'UPDATE_MODE_OF_WORK_REQUEST',
    UPDATE_MODE_OF_WORK_SUCESS: 'UPDATE_MODE_OF_WORK_SUCESS',
    UPDATE_MODE_OF_WORK_FAILED: 'UPDATE_MODE_OF_WORK_FAILED',

    REMOVE_MODE_OF_WORK_REQUEST: 'REMOVE_MODE_OF_WORK_REQUEST',
    REMOVE_MODE_OF_WORK_SUCESS: 'REMOVE_MODE_OF_WORK_SUCESS',
    REMOVE_MODE_OF_WORK_FAILED: 'REMOVE_MODE_OF_WORK_FAILED',

    // Interview Type master
    GET_ALL_INTERVIEW_TYPE_REQUEST: 'GET_ALL_INTERVIEW_TYPE_REQUEST',
    GET_ALL_INTERVIEW_TYPE_SUCESS: 'GET_ALL_INTERVIEW_TYPE_SUCESS',
    GET_ALL_INTERVIEW_TYPE_FAILED: 'GET_ALL_INTERVIEW_TYPE_FAILED',

    GET_ACTIVE_INTERVIEW_TYPE_REQUEST: 'GET_ACTIVE_INTERVIEW_TYPE_REQUEST',
    GET_ACTIVE_INTERVIEW_TYPE_SUCESS: 'GET_ACTIVE_INTERVIEW_TYPE_SUCESS',
    GET_ACTIVE_INTERVIEW_TYPE_FAILED: 'GET_ACTIVE_INTERVIEW_TYPE_FAILED',

    ADD_INTERVIEW_TYPE_REQUEST: 'ADD_INTERVIEW_TYPE_REQUEST',
    ADD_INTERVIEW_TYPE_SUCESS: 'ADD_INTERVIEW_TYPE_SUCESS',
    ADD_INTERVIEW_TYPE_FAILED: 'ADD_INTERVIEW_TYPE_FAILED',

    UPDATE_INTERVIEW_TYPE_REQUEST: 'UPDATE_INTERVIEW_TYPE_REQUEST',
    UPDATE_INTERVIEW_TYPE_SUCESS: 'UPDATE_INTERVIEW_TYPE_SUCESS',
    UPDATE_INTERVIEW_TYPE_FAILED: 'UPDATE_INTERVIEW_TYPE_FAILED',

    REMOVE_INTERVIEW_TYPE_REQUEST: 'REMOVE_INTERVIEW_TYPE_REQUEST',
    REMOVE_INTERVIEW_TYPE_SUCESS: 'REMOVE_INTERVIEW_TYPE_SUCESS',
    REMOVE_INTERVIEW_TYPE_FAILED: 'REMOVE_INTERVIEW_TYPE_FAILED',

    // Interview Types List 
    GET_ALL_DEGREE_REQUEST: 'GET_ALL_DEGREE_REQUEST',
    GET_ALL_DEGREE_SUCESS: 'GET_ALL_DEGREE_SUCESS',
    GET_ALL_DEGREE_FAILED: 'GET_ALL_DEGREE_FAILED',

    GET_ACTIVE_DEGREE_REQUEST: 'GET_ACTIVE_DEGREE_REQUEST',
    GET_ACTIVE_DEGREE_SUCESS: 'GET_ACTIVE_DEGREE_SUCESS',
    GET_ACTIVE_DEGREE_FAILED: 'GET_ACTIVE_DEGREE_FAILED',

    ADD_DEGREE_REQUEST: 'ADD_DEGREE_REQUEST',
    ADD_DEGREE_SUCESS: 'ADD_DEGREE_SUCESS',
    ADD_DEGREE_FAILED: 'ADD_DEGREE_FAILED',

    UPDATE_DEGREE_REQUEST: 'UPDATE_DEGREE_REQUEST',
    UPDATE_DEGREE_SUCESS: 'UPDATE_DEGREE_SUCESS',
    UPDATE_DEGREE_FAILED: 'UPDATE_DEGREE_FAILED',

    REMOVE_DEGREE_REQUEST: 'REMOVE_DEGREE_REQUEST',
    REMOVE_DEGREE_SUCESS: 'REMOVE_DEGREE_SUCESS',
    REMOVE_DEGREE_FAILED: 'REMOVE_DEGREE_FAILED',

    // Interview Mode Types List 
    GET_ALL_INTERVIEW_MODE_REQUEST: 'GET_ALL_INTERVIEW_MODE_REQUEST',
    GET_ALL_INTERVIEW_MODE_SUCESS: 'GET_ALL_INTERVIEW_MODE_SUCESS',
    GET_ALL_INTERVIEW_MODE_FAILED: 'GET_ALL_INTERVIEW_MODE_FAILED',

    GET_ACTIVE_INTERVIEW_MODE_REQUEST: 'GET_ACTIVE_INTERVIEW_MODE_REQUEST',
    GET_ACTIVE_INTERVIEW_MODE_SUCESS: 'GET_ACTIVE_INTERVIEW_MODE_SUCESS',
    GET_ACTIVE_INTERVIEW_MODE_FAILED: 'GET_ACTIVE_INTERVIEW_MODE_FAILED',

    ADD_INTERVIEW_MODE_REQUEST: 'ADD_INTERVIEW_MODE_REQUEST',
    ADD_INTERVIEW_MODE_SUCESS: 'ADD_INTERVIEW_MODE_SUCESS',
    ADD_INTERVIEW_MODE_FAILED: 'ADD_INTERVIEW_MODE_FAILED',

    UPDATE_INTERVIEW_MODE_REQUEST: 'UPDATE_INTERVIEW_MODE_REQUEST',
    UPDATE_INTERVIEW_MODE_SUCESS: 'UPDATE_INTERVIEW_MODE_SUCESS',
    UPDATE_INTERVIEW_MODE_FAILED: 'UPDATE_INTERVIEW_MODE_FAILED',

    REMOVE_INTERVIEW_MODE_REQUEST: 'REMOVE_INTERVIEW_MODE_REQUEST',
    REMOVE_INTERVIEW_MODE_SUCESS: 'REMOVE_INTERVIEW_MODE_SUCESS',
    REMOVE_INTERVIEW_MODE_FAILED: 'REMOVE_INTERVIEW_MODE_FAILED',

}


export default Constants